server {
    listen 80;
    server_name _;
    client_max_body_size 128M;

    root /var/www/asxentiq/backend/public;
    index index.php;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass unix:/run/php/php8.2-fpm.sock;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT $document_root;
        fastcgi_param PHP_VALUE "post_max_size=128M
upload_max_filesize=128M
memory_limit=256M";
    }
}
